# Default values for k8s-pod-restart-info-collector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# clusterName: "Change-Me"
# slackWebhookUrl: "https://hooks.slack.com/services/Change-Me"
#slackWebhookUrlSecretKeyRef:
#  key: "slackWebhookUrl"
#  name: "k8s-pod-restart-info-collector"
slackChannel: "restart-info-nonprod"
slackUsername: "k8s-pod-restart-info-collector"
muteSeconds: 600
ignoreRestartCount: 30

# A set of namespaces to be ignored. This should be provided as a comma-separated list or a regular expression.
ignoredNamespaces: ""
# A set of pod name prefixes to be ignored. This should be provided as a comma-separated list or a regular expression.
ignoredPodNamePrefixes: ""

# A set of namespaces to be watched. This should be provided as a comma-separated list or a regular expression.
watchedNamespaces: ""
# A set of pod name prefixes to be watched. This should be provided as a comma-separated list or a regular expression.
watchedPodNamePrefixes: ""

# Whether restart events with an exit code of 0 should be ignored, true or false
ignoreRestartsWithExitCodeZero: false

# A set of allowed restart reasons to be sent. This should be provided as a comma-separated list.
# Example: "OOMKilled.*,Error.*" - that will pass all OOMKilled and Error reasons
allowedRestartReasons: ""

image:
  repository: disparo/k8s-pod-restart-info-collector
  tag: "v1.6.1"
  pullPolicy: IfNotPresent

resources: 
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 20m
    memory: 50Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}
